name = "estimate-server"
type = "javascript"
compatibility_date = "2024-06-22"

# Entry point for the Worker
main = "dist/index.js"

# Optional if using custom domain
# routes = [{ pattern = "api.yourdomain.com/*", zone_id = "..." }]

[build]
command = "bun run build:all"

[define]
NODE_ENV = "production"
