export default [
  { name: 'Euro', label: 'EUR', symbol: '€' },
  { name: 'US Dollar', label: 'USD', symbol: '$' },
  { name: 'British Pound', label: 'GBP', symbol: '£' },
  { name: 'Japanese Yen', label: 'JPY', symbol: '¥' },
  { name: 'Swiss Franc', label: 'CHF', symbol: 'CHF' },
  { name: 'Canadian Dollar', label: 'CAD', symbol: 'C$' },
  { name: 'Australian Dollar', label: 'AUD', symbol: 'A$' },
  { name: 'New Zealand Dollar', label: 'NZD', symbol: 'NZ$' },
  { name: 'Singapore Dollar', label: 'SGD', symbol: 'S$' },
  { name: 'Hong Kong Dollar', label: 'HKD', symbol: 'HK$' },
  { name: 'Nigerian Naira', label: 'NGN', symbol: '₦' },
  { name: 'Ghanaian Cedi', label: 'GHS', symbol: '₵' },
  { name: 'South African Rand', label: 'ZAR', symbol: 'R' },
  { name: 'Indian Rupee', label: 'INR', symbol: '₹' },
  { name: 'Pakistani Rupee', label: 'PKR', symbol: '₨' },
  { name: 'Bangladeshi Taka', label: 'BDT', symbol: '৳' },
  { name: 'Chinese Yuan', label: 'CNY', symbol: '¥' },
  { name: 'Taiwan Dollar', label: 'TWD', symbol: 'NT$' },
  { name: 'South Korean Won', label: 'KRW', symbol: '₩' },
  { name: 'Vietnamese Dong', label: 'VND', symbol: '₫' },
  { name: 'Brazilian Real', label: 'BRL', symbol: 'R$' },
  { name: 'Mexican Peso', label: 'MXN', symbol: 'MX$' },
  { name: 'Argentine Peso', label: 'ARS', symbol: 'ARS$' },
  { name: 'Chilean Peso', label: 'CLP', symbol: 'CLP$' },
  { name: 'Colombian Peso', label: 'COP', symbol: 'COP$' },
  { name: 'Russian Ruble', label: 'RUB', symbol: '₽' },
  { name: 'Turkish Lira', label: 'TRY', symbol: '₺' },
  { name: 'Israeli Shekel', label: 'ILS', symbol: '₪' },
  { name: 'Saudi Riyal', label: 'SAR', symbol: '﷼' },
  { name: 'UAE Dirham', label: 'AED', symbol: 'د.إ' },
  { name: 'Egyptian Pound', label: 'EGP', symbol: 'E£' },
  { name: 'Kenyan Shilling', label: 'KES', symbol: 'KSh' },
  { name: 'Tanzanian Shilling', label: 'TZS', symbol: 'TSh' },
  { name: 'Ethiopian Birr', label: 'ETB', symbol: 'Br' },
  { name: 'Moroccan Dirham', label: 'MAD', symbol: 'MAD' },
  { name: 'Philippine Peso', label: 'PHP', symbol: '₱' },
  { name: 'Malaysian Ringgit', label: 'MYR', symbol: 'RM' },
  { name: 'Indonesian Rupiah', label: 'IDR', symbol: 'Rp' },
  { name: 'Thai Baht', label: 'THB', symbol: '฿' },
  { name: 'Sri Lankan Rupee', label: 'LKR', symbol: 'Rs' },
  { name: 'CFA Franc BCEAO', label: 'XOF', symbol: 'CFA' },
  { name: 'Cuban Peso', label: 'CUP', symbol: '₱' },
  { name: 'Dominican Peso', label: 'DOP', symbol: 'RD$' },
  { name: 'Ukrainian Hryvnia', label: 'UAH', symbol: '₴' },
  { name: 'Polish Zloty', label: 'PLN', symbol: 'zł' },
  { name: 'Hungarian Forint', label: 'HUF', symbol: 'Ft' },
  { name: 'Czech Koruna', label: 'CZK', symbol: 'Kč' },
  { name: 'Swedish Krona', label: 'SEK', symbol: 'kr' },
  { name: 'Norwegian Krone', label: 'NOK', symbol: 'kr' },
  { name: 'Danish Krone', label: 'DKK', symbol: 'kr' },
] as const;
