export default [
  {
    id: 1,
    title: 'Sunny Acres',
    amount: 300.53,
    category: 'Dairy',
    estimates: 12,
  },
  {
    id: 2,
    title: 'Green Pastures',
    amount: 40.89,
    category: 'Crop',
    estimates: 8,
  },
  {
    id: 3,
    title: 'Misty Valley',
    amount: 90.49,
    category: 'Livestock',
    estimates: 15,
  },
  {
    id: 4,
    title: 'Golden Fields',
    amount: 32.27,
    category: 'Wheat',
    estimates: 5,
  },
  {
    id: 5,
    title: 'Blue Sky Ranch',
    amount: 208.2,
    category: 'Mixed',
    estimates: 10,
  },
  {
    id: 6,
    title: 'Whispering Pines',
    amount: 54.05,
    category: 'Dairy',
    estimates: 7,
  },
  {
    id: 7,
    title: 'Rolling Hills',
    amount: 14.69,
    category: 'Vineyard',
    estimates: 14,
  },
  {
    id: 8,
    title: 'Harvest Moon',
    amount: 812.45,
    category: 'Crop',
    estimates: 9,
  },
  {
    id: 9,
    title: 'Tranquil Meadows',
    amount: 81.65,
    category: 'Organic',
    estimates: 11,
  },
  {
    id: 10,
    title: 'Rustic Roots',
    amount: 281.23,
    category: 'Livestock',
    estimates: 6,
  },
  {
    id: 11,
    title: 'Serene Valley',
    amount: 290.23,
    category: 'Dairy',
    estimates: 8,
  },
  {
    id: 12,
    title: 'Prairie Winds',
    amount: 902.21,
    category: 'Crop',
    estimates: 13,
  },
];
