export default [
  // 🌱 Land Preparation
  {
    id: 'icon-001',
    icon: 'leaf',
    group: 'Land Preparation',
    lightColor: '#d1f5d3',
    normalColor: '#2e7d32',
  },
  {
    id: 'icon-002',
    icon: 'construct',
    group: 'Land Preparation',
    lightColor: '#ffe0b2',
    normalColor: '#ef6c00',
  },
  {
    id: 'icon-003',
    icon: 'trail-sign',
    group: 'Land Preparation',
    lightColor: '#f3e5f5',
    normalColor: '#8e24aa',
  },
  {
    id: 'icon-004',
    icon: 'flask',
    group: 'Land Preparation',
    lightColor: '#e1f5fe',
    normalColor: '#0288d1',
  },
  {
    id: 'icon-005',
    icon: 'document-text',
    group: 'Land Preparation',
    lightColor: '#f5f5f5',
    normalColor: '#616161',
  },

  // 🌾 Planting Materials
  {
    id: 'icon-006',
    icon: 'egg',
    group: 'Planting Materials',
    lightColor: '#fff3e0',
    normalColor: '#fb8c00',
  },
  {
    id: 'icon-007',
    icon: 'cut',
    group: 'Planting Materials',
    lightColor: '#fbe9e7',
    normalColor: '#e53935',
  },
  {
    id: 'icon-008',
    icon: 'link',
    group: 'Planting Materials',
    lightColor: '#e1f5fe',
    normalColor: '#039be5',
  },
  {
    id: 'icon-009',
    icon: 'basket',
    group: 'Planting Materials',
    lightColor: '#fce4ec',
    normalColor: '#d81b60',
  },
  {
    id: 'icon-010',
    icon: 'nutrition',
    group: 'Planting Materials',
    lightColor: '#e0f2f1',
    normalColor: '#00796b',
  },

  // 💧 Irrigation & Water
  {
    id: 'icon-011',
    icon: 'water',
    group: 'Irrigation & Water',
    lightColor: '#e3f2fd',
    normalColor: '#1976d2',
  },
  {
    id: 'icon-012',
    icon: 'rainy',
    group: 'Irrigation & Water',
    lightColor: '#b3e5fc',
    normalColor: '#03a9f4',
  },
  {
    id: 'icon-013',
    icon: 'cog',
    group: 'Irrigation & Water',
    lightColor: '#eceff1',
    normalColor: '#607d8b',
  },
  {
    id: 'icon-014',
    icon: 'hammer',
    group: 'Irrigation & Water',
    lightColor: '#fbe9e7',
    normalColor: '#f4511e',
  },
  {
    id: 'icon-015',
    icon: 'hardware-chip',
    group: 'Irrigation & Water',
    lightColor: '#e0e7ff',
    normalColor: '#3b49df',
  },

  // 💼 Labor
  {
    id: 'icon-016',
    icon: 'walk',
    group: 'Labor',
    lightColor: '#fce4ec',
    normalColor: '#c2185b',
  },
  {
    id: 'icon-017',
    icon: 'man',
    group: 'Labor',
    lightColor: '#f3e5f5',
    normalColor: '#7b1fa2',
  },
  {
    id: 'icon-018',
    icon: 'brush',
    group: 'Labor',
    lightColor: '#ede7f6',
    normalColor: '#5e35b1',
  },
  {
    id: 'icon-019',
    icon: 'hand-left',
    group: 'Labor',
    lightColor: '#f0f4c3',
    normalColor: '#afb42b',
  },
  {
    id: 'icon-020',
    icon: 'body',
    group: 'Labor',
    lightColor: '#e8f5e9',
    normalColor: '#43a047',
  },

  // 🧪 Soil Health & Fertilization
  {
    id: 'icon-021',
    icon: 'beaker',
    group: 'Soil Health & Fertilization',
    lightColor: '#e1f5fe',
    normalColor: '#0288d1',
  },
  {
    id: 'icon-022',
    icon: 'trash-bin',
    group: 'Soil Health & Fertilization',
    lightColor: '#fbe9e7',
    normalColor: '#e53935',
  },
  {
    id: 'icon-023',
    icon: 'scale',
    group: 'Soil Health & Fertilization',
    lightColor: '#fff8e1',
    normalColor: '#fbc02d',
  },
  {
    id: 'icon-024',
    icon: 'eyedrop',
    group: 'Soil Health & Fertilization',
    lightColor: '#e1f5fe',
    normalColor: '#039be5',
  },
  {
    id: 'icon-025',
    icon: 'bonfire',
    group: 'Soil Health & Fertilization',
    lightColor: '#ffe0b2',
    normalColor: '#ef6c00',
  },

  // 🐛 Pest, Disease & Weed Control
  {
    id: 'icon-026',
    icon: 'bug',
    group: 'Pest, Disease & Weed Control',
    lightColor: '#fce4ec',
    normalColor: '#e91e63',
  },
  {
    id: 'icon-027',
    icon: 'bandage',
    group: 'Pest, Disease & Weed Control',
    lightColor: '#e1f5fe',
    normalColor: '#0288d1',
  },
  {
    id: 'icon-028',
    icon: 'color-fill',
    group: 'Pest, Disease & Weed Control',
    lightColor: '#fff3e0',
    normalColor: '#fb8c00',
  },
  {
    id: 'icon-029',
    icon: 'medical',
    group: 'Pest, Disease & Weed Control',
    lightColor: '#fbe9e7',
    normalColor: '#d32f2f',
  },
  {
    id: 'icon-030',
    icon: 'pulse',
    group: 'Pest, Disease & Weed Control',
    lightColor: '#f3e5f5',
    normalColor: '#ab47bc',
  },

  // 🏠 Infrastructure
  {
    id: 'icon-031',
    icon: 'bulb',
    group: 'Infrastructure',
    lightColor: '#efebe9',
    normalColor: '#6d4c41',
  },
  {
    id: 'icon-032',
    icon: 'home',
    group: 'Infrastructure',
    lightColor: '#e0f7fa',
    normalColor: '#00acc1',
  },
  {
    id: 'icon-033',
    icon: 'grid',
    group: 'Infrastructure',
    lightColor: '#f3e5f5',
    normalColor: '#8e24aa',
  },
  {
    id: 'icon-034',
    icon: 'sunny',
    group: 'Infrastructure',
    lightColor: '#fff9c4',
    normalColor: '#fdd835',
  },
  {
    id: 'icon-035',
    icon: 'business',
    group: 'Infrastructure',
    lightColor: '#f1f8e9',
    normalColor: '#558b2f',
  },

  // 🚜 Machinery & Equipment
  {
    id: 'icon-036',
    icon: 'car-sport',
    group: 'Machinery & Equipment',
    lightColor: '#e0f2f1',
    normalColor: '#00897b',
  },
  {
    id: 'icon-037',
    icon: 'snow',
    group: 'Machinery & Equipment',
    lightColor: '#ede7f6',
    normalColor: '#5e35b1',
  },
  {
    id: 'icon-038',
    icon: 'push',
    group: 'Machinery & Equipment',
    lightColor: '#fff3e0',
    normalColor: '#ef6c00',
  },
  {
    id: 'icon-039',
    icon: 'terminal',
    group: 'Machinery & Equipment',
    lightColor: '#eceff1',
    normalColor: '#455a64',
  },
  {
    id: 'icon-040',
    icon: 'barcode',
    group: 'Machinery & Equipment',
    lightColor: '#f1f8e9',
    normalColor: '#7cb342',
  },

  // 🐄 Livestock & Animal Inputs
  {
    id: 'icon-041',
    icon: 'paw',
    group: 'Livestock & Animal Inputs',
    lightColor: '#f3e5f5',
    normalColor: '#9c27b0',
  },
  {
    id: 'icon-042',
    icon: 'restaurant',
    group: 'Livestock & Animal Inputs',
    lightColor: '#fff3e0',
    normalColor: '#ff7043',
  },
  {
    id: 'icon-043',
    icon: 'medkit',
    group: 'Livestock & Animal Inputs',
    lightColor: '#fbe9e7',
    normalColor: '#d32f2f',
  },
  {
    id: 'icon-044',
    icon: 'fish',
    group: 'Livestock & Animal Inputs',
    lightColor: '#e0f7fa',
    normalColor: '#00acc1',
  },
  {
    id: 'icon-045',
    icon: 'trophy',
    group: 'Livestock & Animal Inputs',
    lightColor: '#fffde7',
    normalColor: '#fdd835',
  },

  // 📦 Post-Harvest & Marketing
  {
    id: 'icon-046',
    icon: 'cube',
    group: 'Post-Harvest & Marketing',
    lightColor: '#f1f8e9',
    normalColor: '#7cb342',
  },
  {
    id: 'icon-047',
    icon: 'bus',
    group: 'Post-Harvest & Marketing',
    lightColor: '#e3f2fd',
    normalColor: '#039be5',
  },
  {
    id: 'icon-048',
    icon: 'cash',
    group: 'Post-Harvest & Marketing',
    lightColor: '#fff8e1',
    normalColor: '#fbc02d',
  },
  {
    id: 'icon-049',
    icon: 'cart',
    group: 'Post-Harvest & Marketing',
    lightColor: '#fce4ec',
    normalColor: '#d81b60',
  },
  {
    id: 'icon-050',
    icon: 'storefront',
    group: 'Post-Harvest & Marketing',
    lightColor: '#e8f5e9',
    normalColor: '#43a047',
  },
];
